services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ContactFormBundle\Controller\:
        resource: '../../Controller/*'

    c975L\ContactFormBundle\Form\:
        resource: '../../Form/*'

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - name: twig.extension
