services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ContactFormBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\ContactFormBundle\Form\:
        resource: '../src/Form/*'

    c975L\ContactFormBundle\Security\:
        resource: '../src/Security/*'

    c975L\ContactFormBundle\Service\:
        resource: '../src/Service/*'
