services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ContactFormBundle\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Event}'

    c975L\ContactFormBundle\Form\ContactFormFactory:
        arguments:
            $cspListener: '@?nelmio_security.csp_listener'

    c975L\ContactFormBundle\Service\ContactFormService:
        arguments:
            $contactFormByIpLimiterFactory: '@?limiter.contact_form_by_ip'
            $contactFormByEmailLimiterFactory: '@?limiter.contact_form_by_email'

    ui.block.contact_form:
        class: stdClass
        tags:
            - name: ui.block
              kind: contact_form
              label: "Formulaire de contact"
              form: c975L\ContactFormBundle\Form\Block\ContactFormType
              template: '@c975LContactForm/components/ContactForm/ContactFormBlock.html.twig'
              icon: '📬'
              category: 'Forms'